#!/usr/bin/env python3
from pathlib import Path
import json
import time
import sys
import os
import signal

def print_usage():
    print('''Usage: timec <name> <time>''') 

if len(sys.argv) != 3:
   print_usage()
   exit(-1)

os.system('timee start ' + sys.argv[1])
def exit_early(sig, frame):
   os.system('timee stop ' + sys.argv[1])
   sys.exit(0)
signal.signal(signal.SIGINT, exit_early)
time.sleep(int(sys.argv[2]))
print("\07")
os.system('timee stop ' + sys.argv[1])
